---
pages:
- posts/test-post.md
- posts/test3.md
- posts/test2.md
hide_body: false
is_partial: false
fields:
- name: date
  label: Date
  type: field_group
  hidden: false
  default: {}
- type: include
  template: seo
  label: SEO
  name: seo
- type: textarea
  name: testwysi
  label: testwysi
  config:
    wysiwyg: true
    schema:
      format: markdown
